### ISSUE TITLE
About cycle GAN to synthesize pictures

### ISSUE THREAD

**Issue by julingers** [joshi-bharat/deep_underwater_localization#6]
Hello, thank you for your help before. I'm here to disturb you again. 

I have completed the acquisition of the rendered image in the simulation, and successfully obtained the 2D coordinates of the 8 corner points of the 3D model, and now I am making synthetic images. Regarding cycle GAN, I would like to ask you a few questions.

- Do you directly use the code of _**junyanzhu**_ to complete the synthesis of the rendered image? Have you made any changes to the source code？Or just use your own datasets, completely using the source code. Refer to [https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix).
- It seems that the resolution of the pictures synthesized by cycle GAN is very low. How did you get the final high-quality pictures? It looks like your synthetic pictures looks good.

Thanks to you again!

**Comment by joshi-bharat** [comment]
Yes, I changed the code a little bit. I don't remember actually what I changed. But I had to change some of the parameters. 
You can change the output of cyclegan to 800x600 pixels. That's what I did. 

Also, you need to train for large number of epochs and save sample images. Since CycleGAN is descriminator/generator network, there is no guarantee of better result after larger training time. You just choose the epoch where source image look similar to target.

**Comment by julingers** [comment]
@joshi-bharat Hi, I really need your help. Many times I trained with CycleGAN using my AUV images, it seems like no success. Why your sythetic images seems really good, I don't know what's my problem. 

 My images are 1920×1080 pixel, I tried resize, I tried crop, but I just can't get good synthetic results when tested images. I think you trained Aquars images with 1600×1200 pixel, so what preprocess you have done when traning. if resize, it will cause distortion. If random crop, it will get some square images without my auv.
![image](https://user-images.githubusercontent.com/59331333/141229879-039614a8-ae8f-40d6-97e1-d4b7cad8f50e.png)

Here is the traning tip for rectangle images input. As it say, during training, I specified --preprocess crop and --crop_size 512. This will allow cycleGAN model to be trained on randomly cropped 512x512 images during training time. During test time, I applied the model on 1920x1080 images with the flag --preprocess none. But!!!
![19_55_58_real](https://user-images.githubusercontent.com/59331333/141229798-6a12ac10-87b2-40e9-b607-c6411b5427d4.png)
![19_55_58_fake](https://user-images.githubusercontent.com/59331333/141229813-e3fb4916-e126-45d4-b500-eb708e585a17.png)
It looks like bad. Can you help me!!!

**Comment by joshi-bharat** [comment]
I have been busy and I looked up some of the things that would be helpful to you. So, I modified cycleGAN to train with low-resolution images and inference with 800*600 resolution. I also disabled some of the image augmentations for instance color transformation. I created a new data loader DeepCLDataLoader and you can find the code here https://drive.google.com/drive/folders/1ErzkadZK2XaOy7PuKq4Ws8RhMWgVJfJm?usp=sharing.

Apart from that, can you the images you are using as target and source? Since this is adversarial training I suggest you save sample images for every say 5 epochs and then use one which is the best. You are not guaranteed to get the best target domain images at the end.
